# This is a configuration file example for prometheus android exporter.

# Settings specific to exporting metrics using a HTTP server
prometheus_server:

  enabled: false # default
  port: 22322 # default

# Settings specific to pushing metrics to pushprox proxy
# This is handy for traversing network topologies such as NAT
pushprox:

  enabled: true # default
  # fully qualified domain name
  fqdn: "some-fqdn" # string, no default value provided

  proxy_url: "url" # string, no default value provided

# Settings specific to backfilling metrics using prometheus remote write
# 
# Please note that remote_write may be limited by a receiving backend on 
# how old the backfilled time series can be.
remote_write:

  # scrape interval in seconds
  enabled: true # default
  scrape_interval: 60 # default

  # where to post metrics
  remote_write_endpoint: "rem-wrirte" # string, no default value provided
