# Author: Martin Ptacek

# This is a configuration file documentation for Prometheu Android Exporter.
# Place this file at /data/user/0/com.birdthedeveloper.prometheus.Android.exporter/files/config.yaml
# to the android device

# Settings specific to exporting metrics using a HTTP server (Prometheus exporter mode)
prometheus_server:

  enabled: true # default
  port: 10101 # default

# Settings specific to pushing metrics to PushProx proxy server
# This is handy for traversing network topologies such as NAT
pushprox:

  enabled: false # default

  # fully qualified domain name
  # example: test.example.com
  fqdn: # string, no default value provided

  # example: http://example.com:8080
  proxy_url: # string, no default value provided

# Settings for the batch exporter mode
# specific to backfilling metrics using prometheus remote write
# 
# Please note that remote_write may be limited by a receiving backend on 
# how old the backfilled time series can be.
# For prometheus this limit is set to roughly 1 hour
remote_write:

  # scrape interval in seconds
  enabled: false # default
  scrape_interval: 30 # default

  # where to post metrics
  # data type: string, no default value provided
  # example: http://localhost:9090/
  remote_write_endpoint:

  max_samples_per_export: 500 # default

  export_interval: 60 # default

  # instance and job target labels, defaults are provided
  # string values
  instance: "test instance"
  job: "test job"
