# This is a configuration file example for prometheus android exporter.

# Settings specific to exporting metrics using a HTTP server
prometheus_server:

  enabled: true # default
  port: 10101 # default

# Settings specific to pushing metrics to pushprox proxy
# This is handy for traversing network topologies such as NAT
pushprox:

  enabled: false # default
  # fully qualified domain name
  # example: com.example.test
  fqdn: # string, no default value provided

  proxy_url: # string, no default value provided

# Settings specific to backfilling metrics using prometheus remote write
# 
# Please note that remote_write may be limited by a receiving backend on 
# how old the backfilled time series can be.
# For prometheus this limit is set to 1 hour
remote_write:

  # scrape interval in seconds
  enabled: false # default
  scrape_interval: 30 # default

  # where to post metrics
  # data type: string, no default value provided
  # example: http://localhost:9090/
  remote_write_endpoint:

  # default value is 5 scrapes 
  max_samples_per_send: 5
