# Author: Martin Ptacek

# Prometheus global configuration file
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
scrape_configs:
  - job_name: "prometheus"

    static_configs:
      - targets: ["localhost:9090"] # scrape prometheus itself
        labels:
          backfill: 'false'

  
  - job_name: "android phones"
    proxy_url: "http://pushprox:8080"
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: [
          "test.example.com"
        ]
        labels:
          backfill: 'false'
