# run this playbook against new linux server

- name: Install example server stack for prometheus-exporter-android
  hosts: android-prometheus-exporter-target-server
  remote_user: root

  tasks:
    - name: Assert linux distribution is Rocky Linux

    - name: Install docker

    - name: Install docker compose

    - name: Create user androidexporter

    - name: 


#TODO create user androidexporter
#TODO install docker
#TODO install docker compose
#TODO copy files over
#TODO create folder structure